package com.metes.worthit.core.designsystem.component.defaults

import androidx.compose.foundation.text.selection.TextSelectionColors
import androidx.compose.material3.TextFieldColors
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import com.metes.worthit.core.designsystem.theme.AppTheme

object WorthItOutlinedTextFieldDefaults {
    @Composable
    fun colors(
        focusedTextColor: Color = AppTheme.colorScheme.onBackground,
        unfocusedTextColor: Color = AppTheme.colorScheme.onBackground,
        disabledTextColor: Color = AppTheme.colorScheme.secondary,
        errorTextColor: Color = AppTheme.colorScheme.onBackground,
        focusedContainerColor: Color = Color.Transparent,
        unfocusedContainerColor: Color = Color.Transparent,
        disabledContainerColor: Color = Color.Transparent,
        errorContainerColor: Color = Color.Transparent,
        cursorColor: Color = AppTheme.colorScheme.primary,
        errorCursorColor: Color = AppTheme.colorScheme.error,
        textSelectionColors: TextSelectionColors = TextSelectionColors(
            handleColor = AppTheme.colorScheme.primary,
            backgroundColor = AppTheme.colorScheme.primary.copy(alpha = 0.3f)
        ),
        focusedIndicatorColor: Color = AppTheme.colorScheme.primary,
        unfocusedIndicatorColor: Color = AppTheme.colorScheme.secondary,
        disabledIndicatorColor: Color = AppTheme.colorScheme.secondary.copy(alpha = 0.5f),
        errorIndicatorColor: Color = AppTheme.colorScheme.error,
        focusedLabelColor: Color = AppTheme.colorScheme.primary,
        unfocusedLabelColor: Color = AppTheme.colorScheme.secondary,
        disabledLabelColor: Color = AppTheme.colorScheme.secondary.copy(alpha = 0.5f),
        errorLabelColor: Color = AppTheme.colorScheme.error,
        focusedLeadingIconColor: Color = AppTheme.colorScheme.primary,
        unfocusedLeadingIconColor: Color = AppTheme.colorScheme.secondary,
        disabledLeadingIconColor: Color = AppTheme.colorScheme.secondary.copy(alpha = 0.5f),
        errorLeadingIconColor: Color = AppTheme.colorScheme.error,
        focusedTrailingIconColor: Color = AppTheme.colorScheme.primary,
        unfocusedTrailingIconColor: Color = AppTheme.colorScheme.secondary,
        disabledTrailingIconColor: Color = AppTheme.colorScheme.secondary.copy(alpha = 0.5f),
        errorTrailingIconColor: Color = AppTheme.colorScheme.error,
        focusedPlaceholderColor: Color = AppTheme.colorScheme.secondary,
        unfocusedPlaceholderColor: Color = AppTheme.colorScheme.secondary,
        disabledPlaceholderColor: Color = AppTheme.colorScheme.secondary.copy(alpha = 0.5f),
        errorPlaceholderColor: Color = AppTheme.colorScheme.secondary,
        focusedSupportingTextColor: Color = AppTheme.colorScheme.secondary,
        unfocusedSupportingTextColor: Color = AppTheme.colorScheme.secondary,
        disabledSupportingTextColor: Color = AppTheme.colorScheme.secondary.copy(alpha = 0.5f),
        errorSupportingTextColor: Color = AppTheme.colorScheme.error,
        focusedPrefixColor: Color = AppTheme.colorScheme.onBackground,
        unfocusedPrefixColor: Color = AppTheme.colorScheme.onBackground,
        disabledPrefixColor: Color = AppTheme.colorScheme.secondary.copy(alpha = 0.5f),
        errorPrefixColor: Color = AppTheme.colorScheme.onBackground,
        focusedSuffixColor: Color = AppTheme.colorScheme.onBackground,
        unfocusedSuffixColor: Color = AppTheme.colorScheme.onBackground,
        disabledSuffixColor: Color = AppTheme.colorScheme.secondary.copy(alpha = 0.5f),
        errorSuffixColor: Color = AppTheme.colorScheme.onBackground,
    ): TextFieldColors = TextFieldColors(
        focusedTextColor = focusedTextColor,
        unfocusedTextColor = unfocusedTextColor,
        disabledTextColor = disabledTextColor,
        errorTextColor = errorTextColor,
        focusedContainerColor = focusedContainerColor,
        unfocusedContainerColor = unfocusedContainerColor,
        disabledContainerColor = disabledContainerColor,
        errorContainerColor = errorContainerColor,
        cursorColor = cursorColor,
        errorCursorColor = errorCursorColor,
        textSelectionColors = textSelectionColors,
        focusedIndicatorColor = focusedIndicatorColor,
        unfocusedIndicatorColor = unfocusedIndicatorColor,
        disabledIndicatorColor = disabledIndicatorColor,
        errorIndicatorColor = errorIndicatorColor,
        focusedLabelColor = focusedLabelColor,
        unfocusedLabelColor = unfocusedLabelColor,
        disabledLabelColor = disabledLabelColor,
        errorLabelColor = errorLabelColor,
        focusedLeadingIconColor = focusedLeadingIconColor,
        unfocusedLeadingIconColor = unfocusedLeadingIconColor,
        disabledLeadingIconColor = disabledLeadingIconColor,
        errorLeadingIconColor = errorLeadingIconColor,
        focusedTrailingIconColor = focusedTrailingIconColor,
        unfocusedTrailingIconColor = unfocusedTrailingIconColor,
        disabledTrailingIconColor = disabledTrailingIconColor,
        errorTrailingIconColor = errorTrailingIconColor,
        focusedPlaceholderColor = focusedPlaceholderColor,
        unfocusedPlaceholderColor = unfocusedPlaceholderColor,
        disabledPlaceholderColor = disabledPlaceholderColor,
        errorPlaceholderColor = errorPlaceholderColor,
        focusedSupportingTextColor = focusedSupportingTextColor,
        unfocusedSupportingTextColor = unfocusedSupportingTextColor,
        disabledSupportingTextColor = disabledSupportingTextColor,
        errorSupportingTextColor = errorSupportingTextColor,
        focusedPrefixColor = focusedPrefixColor,
        unfocusedPrefixColor = unfocusedPrefixColor,
        disabledPrefixColor = disabledPrefixColor,
        errorPrefixColor = errorPrefixColor,
        focusedSuffixColor = focusedSuffixColor,
        unfocusedSuffixColor = unfocusedSuffixColor,
        disabledSuffixColor = disabledSuffixColor,
        errorSuffixColor = errorSuffixColor,
    )
}
